### ISSUE TITLE
When will EDAS extend be updated to support the latest version 2.7.0

### ISSUE THREAD

**Issue by liaow** [apache/incubator-dubbo#3594]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: MAC
* Java version: 1.8

### Steps to reproduce this issue

1. update dubbo to 2.7.0
2. update edas-dubbo-extension to 1.0.4
3. start app

### Expected Result

services successfully registery to edas config center

### Actual Result

java.lang.IllegalStateException: Failed to load extension class(interface: interface org.apache.dubbo.registry.RegistryFactory, class line: com.alibaba.edas.dubbo.EdasRegistryFactory) in jar, cause: com.alibaba.dubbo.registry.support.AbstractRegistryFactory

```
java.lang.IllegalStateException: Failed to load extension class(interface: interface org.apache.dubbo.registry.RegistryFactory, class line: com.alibaba.edas.dubbo.EdasRegistryFactory) in jar:file:/Users/nobody/.m2/repository/com/alibaba/edas/edas-dubbo-extension/1.0.4/edas-dubbo-extension-1.0.4.jar!/META-INF/dubbo/com.alibaba.dubbo.registry.RegistryFactory, cause: com.alibaba.dubbo.registry.support.AbstractRegistryFactory
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:675) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:643) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:624) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:595) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensions(ExtensionLoader.java:373) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.extension.factory.SpiExtensionFactory.getExtension(SpiExtensionFactory.java:32) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.extension.factory.AdaptiveExtensionFactory.getExtension(AdaptiveExtensionFactory.java:47) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:562) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:529) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:344) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:553) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:402) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:363) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:345) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:318) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:112) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:58) ~[dubbo-2.7.0.jar:2.7.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at com.copote.nstamp.AuthRpcServiceApplication.main(AuthRpcServiceApplication.java:25) [classes/:na]
Caused by: java.lang.NoClassDefFoundError: com.alibaba.dubbo.registry.support.AbstractRegistryFactory
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_192]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_192]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:672) ~[dubbo-2.7.0.jar:2.7.0]
	... 29 common frames omitted
```

**Comment by ralf0131** [comment]
Hi, 

Thanks for reporting. I have contacted the support from EDAS, and will get back to you as soon as possible. IMO, future report should go to EDAS, not here.

**Comment by liaow** [comment]
Thanks for reply. i will open a new ticket at Alibaba cloud console ask for help too

**Comment by ralf0131** [comment]
Hi, I did confirm with support from EDAS, they confirm that edas-dubbo-extension would fail on 2.7.0, they are looking into this issue. 

The issue on Dubbo side is when you are writing a custom plugin that depends on dubbo 2.6.x, it is possible that it will fail when upgrading to 2.7.x, the compatibility is not 100% guaranteed. For example, if your plugin depends on com.alibaba.dubbo.registry.support.AbstractRegistry, there is no compatible class provided in 2.7.x. 

The community is addressing this issue, and will notify you when there is an update.

**Comment by flystar32** [comment]
change edas-dubbo-extension version to 2.0.1 will work.

edas-dubbo-extension `2.x.x` is compatible with dubbo  2.7.x

edas-dubbo-extension `1.x.x` is compatible with dubbo  between 2.6.0 and 2.7.0

**Comment by mostcool** [comment]
where is edas-dubbo-extension 2.x.x and 1.x.x?

**Comment by flystar32** [comment]
@mostcool  search it in maven central directly, you can also refer to EDAS documents here https://help.aliyun.com/document_detail/97471.html

**Comment by liaow** [comment]
Thanks for working efficiently
